[package]
name = "infinite-escape-velocity"
version = "0.1.0"
authors = ["Grant Jennings <gajbooks@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"
dashmap = { version = "4.0.2", features= ["rayon"] }
tiny-skia = "0.5.1"
crossbeam-channel = "0.5.1"
rayon = "1.5"
macroquad = "0.3"

[profile.release]
lto = true
codegen-units=1
