[package]
name = "infinite-escape-velocity"
version = "0.1.0"
authors = ["Grant Jennings <gajbooks@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version="0.6", features=["ws"] }
clap = { version = "4", features = ["derive"] }
dashmap = "5"
euclid = "0.22"
fxhash = "0.2"
futures = "0.3"
futures-util = "0.3"
num = "0.4"
rayon = "1.5"
rmp-serde = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4", features = ["fs", "trace"] }
ts-rs = { version="7" }
walkdir = "2"

[profile.release]
lto = true
codegen-units=1
debug = true

[profile.dev.package."*"]
opt-level = 3
debug = false
